spring.application.name=fsad-back

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:11123/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=EAOYNTsFNBfAWnChuNcebvqNHiGZwYeY
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=none

spring.datasource.hikari.maximum-pool-size=3

server.port=${PORT:8080}